[tool.ruff]
exclude = [
    ".venv",
]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501", "E731"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"